.TH "AbstractItem" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractItem \- Partial implementation of the \fBItem\fP interface\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractItem\fP"
.br
.RI "Partial implementation of the \fBItem\fP interface\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Partial implementation of the \fBItem\fP interface\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "def AbstractItem\&.main ()"

.PP
Definition at line 100 of file AbstractItem\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
