.TH "AbstractItem.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractItem.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractItem\&.AbstractItem\fP"
.br
.RI "Partial implementation of the \fBItem\fP interface\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAbstractItem\fP"
.br
.RI "Partial implementation of the \fBItem\fP interface\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBAbstractItem\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
