.TH "Customer" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Customer \- A class describing a customer of the Video Store\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomer\fP"
.br
.RI "A \fBCustomer\fP is a client of a \fBVideoStore\fP who can rent items\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class describing a customer of the Video Store\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "def Customer\&.main ()"

.PP
Definition at line 132 of file Customer\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
