.TH "Customer.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Customer.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomer\&.Customer\fP"
.br
.RI "A \fBCustomer\fP is a client of a \fBVideoStore\fP who can rent items\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCustomer\fP"
.br
.RI "A class describing a customer of the Video Store\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBCustomer\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
