.TH "GenreSearch" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenreSearch \- Class for searching items matching a given genre\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenreSearch\fP"
.br
.RI "Implementation of \fBSearchCondition\fP that matches items based on the genre (not case sensitive)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class for searching items matching a given genre\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
