.TH "GenreSearch.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenreSearch.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenreSearch\&.GenreSearch\fP"
.br
.RI "Implementation of \fBSearchCondition\fP that matches items based on the genre (not case sensitive)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGenreSearch\fP"
.br
.RI "Class for searching items matching a given genre\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
