.TH "Item.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Item.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\&.Item\fP"
.br
.RI "This is an abstract class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBItem\fP"
.br
.RI "A class modeling an item of the Video Store\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
