.TH "SearchCondition" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchCondition \- A search predicate for items\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSearchCondition\fP"
.br
.RI "Abstraction of a search predicate for items\&. "
.in -1c
.SH "Detailed Description"
.PP 
A search predicate for items\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
