.TH "SimpleDate" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleDate \- Packages dates in the format yyyy-mm-dd\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleDate\fP"
.br
.RI "Date consisting of a year, month, and day\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Packages dates in the format yyyy-mm-dd\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "def SimpleDate\&.main ()"

.PP
Definition at line 71 of file SimpleDate\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
