.TH "SimpleDate.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleDate.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleDate\&.SimpleDate\fP"
.br
.RI "Date consisting of a year, month, and day\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSimpleDate\fP"
.br
.RI "Packages dates in the format yyyy-mm-dd\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBSimpleDate\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
