.TH "StatusException.StatusException" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatusException.StatusException \- Exception type thrown for invalid operations such as attempting to rent an item that is already rented\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBmsg\fP)"
.br
.RI "Constructs a \fBStatusException\fP with the given message\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmsg\fP"
.br
.RI "hold the error message\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception type thrown for invalid operations such as attempting to rent an item that is already rented\&. 
.PP
Definition at line 16 of file StatusException\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def StatusException\&.StatusException\&.__init__ ( self,  msg)"

.PP
Constructs a \fBStatusException\fP with the given message\&. 
.PP
\fBParameters:\fP
.RS 4
\fImsg\fP message for this exception 
.RE
.PP

.PP
Definition at line 22 of file StatusException\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "StatusException\&.StatusException\&.msg"

.PP
hold the error message\&. 
.PP
Definition at line 26 of file StatusException\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
