.TH "StatusException" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatusException \- Exceptions to be thrown when an error has occurred\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatusException\fP"
.br
.RI "Exception type thrown for invalid operations such as attempting to rent an item that is already rented\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exceptions to be thrown when an error has occurred\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
