.TH "StatusException.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatusException.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatusException\&.StatusException\fP"
.br
.RI "Exception type thrown for invalid operations such as attempting to rent an item that is already rented\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBStatusException\fP"
.br
.RI "Exceptions to be thrown when an error has occurred\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
