.TH "VideoStore.py" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VideoStore.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVideoStore\&.VideoStore\fP"
.br
.RI "\fBVideoStore\fP consists of a list of items and a list of customers who can rent items\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBVideoStore\fP"
.br
.RI "A video store that rents DVDs, and Games\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBVideoStore\&.main\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
