.TH "VideoStore" 3 "Fri Jul 14 2017" "Version 1.0" "Video_Store" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VideoStore \- A video store that rents DVDs, and Games\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVideoStore\fP"
.br
.RI "\fBVideoStore\fP consists of a list of items and a list of customers who can rent items\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A video store that rents DVDs, and Games\&. 


.PP
\fBAuthor:\fP
.RS 4
Paulo Roma 
.RE
.PP
\fBSince:\fP
.RS 4
11/07/2017 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "def VideoStore\&.main ()"

.PP
Definition at line 93 of file VideoStore\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Video_Store from the source code\&.
