Video_Store: AbstractItem.AbstractItem Class Reference
AbstractItem.AbstractItem Class Reference
Partial implementation of the Item interface.
Public Member Functions
def __init__ (self, title, genre, barcode)
Constructs a new Item with the given title, genre, and barcode.
def isRented (self)
Returns whether this item is rented.
def getDueDate (self)
Returns this item due date.
def getTitle (self)
Returns this item title.
def getBarcode (self)
Returns this item barcode.
def __str__ (self)
Returns a representation of the state of this object as a multiline string.
def __eq__ (self, obj)
Determines whether this item is the same as another one based on its barcode.
Public Member Functions inherited from Item.Item
def setRented (self, today)
Rents this item if it is not already rented and sets the due date.
def setReturned (self, today)
Returns this item, if it is currently rented.
def getRentalCost (self)
Returns the cost to rent this item.
def calculateLateFee (self, today)
Calculates the late fee (or bonus) that would be charged (or applied) for returning the item on the given date.
def getGenre (self)
Returns a String representing the genre of this item.
def isRented (self)
Determines whether this item is currently rented.
def getDueDate (self)
Returns the due date for this item if it is currently rented, or null if the item is not rented.
def getTitle (self)
Returns the title of this item.
def getBarcode (self)
Returns the integer barcode for this item.
Private Attributes
__title
Title of this item.
__genre
Genre of this item.
__barcode
Unique Barcode for this item.
__rented
Rental status of this item.
__dueDate
Due date for this item.
Detailed Description
Partial implementation of the Item interface.
Definition at line 16 of file AbstractItem.py.
Constructor & Destructor Documentation
__init__()
def AbstractItem.AbstractItem.__init__ (self, title, genre, barcode)
Constructs a new Item with the given title, genre, and barcode.
This constructor may only be invoked by subclasses.
Parameters
title the title of the item
genre the genre of the item
barcode a unique integer identifier for the item
Definition at line 25 of file AbstractItem.py.
Member Function Documentation
__eq__()
def AbstractItem.AbstractItem.__eq__ (self, obj)
Determines whether this item is the same as another one based on its barcode.
Parameters
obj the object to compare to this item
Returns
true if the given object is an AbstractItem with the same barcode as this one
Definition at line 95 of file AbstractItem.py.
References AbstractItem.AbstractItem.getBarcode().
__str__()
def AbstractItem.AbstractItem.__str__ (self)
Returns a representation of the state of this object as a multiline string.
The format is:
    type
    title
    (genre)
    status
The status is either
    Rented: yyyy-mm-dd
or
    Available
where "yyyy-mm-dd" is the current due date.
Returns
a string representation of this object
Definition at line 76 of file AbstractItem.py.
References AbstractItem.AbstractItem.getDueDate(), Item.Item.getGenre(), AbstractItem.AbstractItem.getTitle(), and AbstractItem.AbstractItem.isRented().
getBarcode()
def AbstractItem.AbstractItem.getBarcode (self)
Returns this item barcode.
Definition at line 52 of file AbstractItem.py.
References AbstractItem.AbstractItem.__barcode.
Referenced by AbstractItem.AbstractItem.__eq__().
getDueDate()
def AbstractItem.AbstractItem.getDueDate (self)
Returns this item due date.
Definition at line 42 of file AbstractItem.py.
References AbstractItem.AbstractItem.__dueDate.
Referenced by AbstractItem.AbstractItem.__str__().
getTitle()
def AbstractItem.AbstractItem.getTitle (self)
Returns this item title.
Definition at line 48 of file AbstractItem.py.
References AbstractItem.AbstractItem.__title.
Referenced by AbstractItem.AbstractItem.__str__().
isRented()
def AbstractItem.AbstractItem.isRented (self)
Returns whether this item is rented.
Definition at line 38 of file AbstractItem.py.
References AbstractItem.AbstractItem.__rented.
Referenced by AbstractItem.AbstractItem.__str__().
Member Data Documentation
__barcode
AbstractItem.AbstractItem.__barcode private
Unique Barcode for this item.
Definition at line 31 of file AbstractItem.py.
Referenced by AbstractItem.AbstractItem.getBarcode().
__dueDate
AbstractItem.AbstractItem.__dueDate private
Due date for this item.
Definition at line 35 of file AbstractItem.py.
Referenced by AbstractItem.AbstractItem.getDueDate().
__genre
AbstractItem.AbstractItem.__genre private
Genre of this item.
Definition at line 29 of file AbstractItem.py.
Referenced by GenreSearch.GenreSearch.matches().
__rented
AbstractItem.AbstractItem.__rented private
Rental status of this item.
Definition at line 33 of file AbstractItem.py.
Referenced by AbstractItem.AbstractItem.isRented().
__title
AbstractItem.AbstractItem.__title private
Title of this item.
Definition at line 27 of file AbstractItem.py.
Referenced by AbstractItem.AbstractItem.getTitle().
The documentation for this class was generated from the following file:
AbstractItem.py